main: update models and migration files (bug 1869032)
mozilla-conduit/lando-prototype pull request #17
Opened 2023-12-13 18:55 UTC by zzzeid

WIP DO NOT MERGE

2024-01-30 21:43 UTC, zzzeid commented
Bit of feature creep, but I know that we've previously discussed changing the way we store patches, and this is quite a simple change that I thought we could include here.

2024-01-30 22:02 UTC, cgsheeh requested changes

2024-01-30 22:02 UTC, cgsheeh commented on src/lando/main/models/configuration.py
> +        except record.DoesNotExist:
Should this be `cls.DoesNotExist`?

2024-01-30 22:04 UTC, cgsheeh commented
> Bit of feature creep, but I know that we've previously discussed changing the way we store patches, and this is quite a simple change that I thought we could include here.

Yes, I was going to make a comment about that but I came to the same conclusion as you. With the `patch_bytes` shim I think we should be covered on that front.

I know this is probably on your mind as well but the sooner we can get the existing LandoAPI tests running in this prototype the more confidence we will have about making such changes. :)

2024-01-31 16:21 UTC, cgsheeh approved these changes

2024-01-31 20:23 UTC, merged